### PR TITLE
Add Hardware Eraser and Auto Draw scripts

### PR DESCRIPTION
**Pull request by threethan**
I wrote and added two scripts for pen users.

---

## Hardware Eraser Support
Detects when an inverted pen is being used, and automatically selects the eraser tool. When released, it switches back to the previously selected tool. (Due to some odd behavior when changing tool on or after pointerdown, it needs to manually delete the erased elements. This shouldn't really effect the user, though.)

## Auto Draw for Pen
When the Select tool is selected, and a pen is hovering, this script will automatically switch to the Free Draw tool. If no pen is detected for half a second, it switches back.

---

Both of them run persistently, in that they only need to be activated once unless Obsidian is reloaded. It would be nice to have more proper support for that sort of thing.
For now I'm running them with the command palette automatically on startup using a [Commander](https://github.com/daaru00/obsidian-commander) macro.

### CODE REVIEW

**Comment by leumasme** [comment]
Briefly tested and can confirm both to work nicely on my Lenovo ThinkBook 14s Yoga

**Comment by zsviczian** [comment]
ups... I missed these. I will test them this coming week and merge them. Thanks & sorry for missing these!

**Comment by MahmadSharaf** [comment]
@threethan Thank you for the scripts.

I have Samsung Tab S8+ and installed Hardware Erasser Support, but the side key, of the S-pen, opens the context window instead of switching to eraser tool.

**Comment by zsviczian** [comment]
I've not noticed this until now... in my old note 8 the pen button did not generate a javascript event.... now it does so we can work with that. I will look into this to see if I can differentiate this event from the right click...

**Comment by MahmadSharaf** [comment]
Yeah! That would be great. Thanks, @zsviczian

**Pull request merged**
