### PR TITLE
An Excalidraw Automate Script for creating mindmap like lines

### PR DESCRIPTION
**Pull request by xllowl**

### CODE REVIEW

**Comment by zsviczian** [comment]
Hi! Thanks for this script!… and apologies for the long delay in responding to your PR. I am traveling on holiday and frankly this is the first time I looked at the git repository in about 5 days. I will try to add it to the library today.

**Comment by xllowl** [comment]
Thanks.
I wish you a good holiday.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月20日(星期三) 下午2:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zsviczian/obsidian-excalidraw-plugin] An Excalidraw Automate Script for creating mindmap like lines (PR #702)





 
Hi! Thanks for this script!… and apologies for the long delay in responding to your PR. I am traveling on holiday and frankly this is the first time I looked at the git repository in about 5 days. I will try to add it to the library today.

**Comment by zsviczian** [comment]
I love this script. This is very useful.

I made a few cosmetic changes to the code and removed unused and unnecessary parts (adding settings to Excalidraw scripts that are later not used will only clutter settings).

You need to do a bit more debugging though, because in certain situations the code miscalculates connectors. See attached video.

It seems like the distance between the first rectangle and the child rectangles will influence how your calculation works, and sometimes results in “reverse” lines.

https://user-images.githubusercontent.com/14358394/180215508-77f7a59c-ac78-47ea-a46e-796fb70cc2ea.MOV

**Comment by xllowl** [comment]
🌝I will try to fix it.

**Comment by zsviczian** [comment]
I love this script!
Next challenge is to make it work to the left and up as well :)

**Pull request merged**
