### PR TITLE
grid selected images

### PR DESCRIPTION
**Pull request by 7flash**

### CODE REVIEW

**Comment by zsviczian** [comment]
@7flash, just letting you know that I have noticed your PRs. I am traveling currently on holiday and only have my iPad at hand. This makes testing PR and responding to issues much slower. I’ll try to look at your PRs and process them, but please understand it might take up to two weeks depending on cricumstances…

**Comment by zsviczian** [comment]
Thank you for submitting this script!!!

I finally found time to test it. I recommend a couple of changes before the script is published to the script library:
- I tried your script with elements that also included lines, arrows, text, and freedraw lines. The result was quite messy. I recommend that you test with these elements, or that your filter `selectedElements` to include only allowed elements (images, rectangles, diamonds, and ellipses). Alternatively, you should test your script logic to work with all sorts of elements in many different arrangments.
- I recommend prompting the user for a padding value and a number of columns value, or to make these into settings. You assume default padding of 0, but the script would be more powerful if it allowed custom padding. Also, I don't understand the logic of `width/topLeftEl.width` what is your intention with this?
- Currently, if images do not have the same aspect ratio, they will be distorted. I recommend maintaining the aspect ratio and centering images within their grid cell

**Comment by 7flash** [comment]
@zsviczian thanks for review!

Will commit fixes:

- Filtering (intended usage with pictures only)
- Padding variable (but no prompt for faster workflow)
- Centering images (adding empty margin space around)

The intention of "width/topLeftEl.width" is calculate number of columns to fill the space in between of first and last elements. In my workflow, I do often insert many screenshots to compare things next to each other, - then I am able to understand the subject through comparison. It almost became essence of my thinking process.

**Comment by 7flash** [comment]
Please review updated script which preserves aspect ratio

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Pull request merged**
